# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
# importing the NumPy library

import numpy as np

In [2]:
#Array 'arange' Function
#Description
#Create an array of first 10 multiples of 5 using the 'arange' function.
multipleof5 = np.arange(5,51,5)
print(multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


Create border array
Description
Given a single integer n, create an (n x n) 2D array with 1 on the border and 0 on the inside.

Note: Make sure the array is of type int.

Example:
Input 1:
4
Output 1:
[[1 1 1 1]
[1 0 0 1]
[1 0 0 1]
[1 1 1 1]]
Input 2:
2
Output 2:
[[1 1] 
 [1 1]] 

In [5]:
n = 4

import numpy as np

border_array = np.ones((n, n), dtype = int)
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [11]:
import numpy as np
n = 2

arrayhj=np.resize([0,1], n)

arrayhj


array([1, 0])

In [25]:
n=2
def printcheckboard(n):
    final = []
    for i in range(n):
        final.append(list(np.tile([0,1],int(n/2))) if i%2==0 else list(np.tile([1,0],int(n/2))))
    print(np.array(final))
printcheckboard(n)

[[0 1]
 [1 0]]


In [29]:
n=4
final = []
for i in range(n):
    final.append(list(np.tile([0,1],int(n/2))) if i%2==0 else list(np.tile([1,0],int(n/2))))
print(np.array(final))


[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [44]:
m=np.array(range(1, 11*12+1)).reshape(11,12)
m

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [45]:
np.unravel_index(99, (11,12))

(8, 3)

In [46]:
np.reshape(p, -1)

NameError: name 'p' is not defined

In [ ]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = 


# creating an array of zeroes with 5 elements
np_2 = 

In [ ]:
# checking the created array: np_1
print(np_1)

In [ ]:
# checking the created array:np_2
print(np_2)

In [ ]:
# data type of np_2


In [ ]:
# specifying the data type of the array in the provided attribute



In [ ]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

In [ ]:
# check the dimension of the arrays
# array np_1


In [ ]:
# check the dimension of the arrays
# array np_2


In [ ]:
# creating a third array with all the 5 elements as ones

np_3 = 

# checking the created array:np_3
print(np_3)

In [ ]:
# check the dimension of the arrays
# array np_2


In [ ]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

In [ ]:
# creating an array of fixed length
np_4 = 

# checking the created array:np_4
print(np_4)

In [ ]:
# checking the created array:np_1
np_1

In [ ]:
# squaring the terms of np_1


In [ ]:
# getting the absolute value of the elements


In [ ]:
# np.sin()
# np.cos()

In [ ]:
# np.log()

### Empty arrays

In [ ]:
# Creating empty arrays

x = np.arange(1, 6)
y = 

# filling the empty array


In [ ]:
# printing the output obtained above
y

### Aggregation of array elements

In [ ]:
# Reducing the elements to a single value based on addition


In [ ]:
# Cummulative addition of elements at each element


In [ ]:
np.linalg

In [13]:
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [ ]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

In [ ]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

In [ ]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

In [ ]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

In [ ]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

In [ ]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))