In [1]:
# Installing the required library
!pip install numpy

In [2]:
# Importing important libraries
import numpy as np

In [3]:
# Creating a 5X4 array
array = np.arange(20).reshape(5,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [4]:
# Finding the maximum value
print('Maximum Value :', np.argmax(array))

Maximum Value : 19


In [5]:
# Finding the minimum value
print('Minimum Value :', np.argmin(array))

Minimum Value : 0


In [8]:
# Checking the shape of our array
print('Shape :', array.shape)

Shape : (5, 4)


In [9]:
# Total data points in array
print('Size :', array.size)

Size : 20


In [11]:
# Taking all the rows but only 1st column
array[:, 0]

array([ 0,  4,  8, 12, 16])

In [12]:
# Taking all the columns but only 1st row
array[0, :]

array([0, 1, 2, 3])

In [16]:
# Taking 1st and 2nd row along with 3rd and 4th column
array[0:2, 2:4]

array([[2, 3],
       [6, 7]])

In [14]:
# Mean Value in array
print('Mean :', np.mean(array))

Mean : 9.5


In [15]:
# Mean Value in array
print('Median :', np.median(array))

Median : 9.5


In [18]:
# Counting values greater than 7
np.count_nonzero(array > 7)

12

In [19]:
# Getting cumulative sum
cumscores = np.cumsum(array)

# Searching for how many values are required for cumulative sum = 20
np.searchsorted(cumscores, 20)

6

In [20]:
# Exploring cumscores
cumscores

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190])

In [22]:
# sum()
np.sum(array)

190